{% set name = "flakeheaven" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flakeheaven-{{ version }}.tar.gz
  sha256: 8644da879bbeae7d2acfffa64f0e68994a9f5f67761cba91b7a8b9970f6ffeb1

build:
  entry_points:
    - flake8heavened = flakeheaven:flake8_entrypoint
    - flakeheaven = flakeheaven:entrypoint
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.7.0
  run:
    - colorama
    - entrypoints
    - flake8 >=4.0.1,<5.0.0
    # Only required for [py<38] but always include so this can be noarch: python
    - importlib-metadata >=1.0,<2.0
    - pygments
    - python >=3.7.0
    - toml
    - urllib3

test:
  imports:
    - flakeheaven
  commands:
    - pip check
    - flake8heavened --help
    - flakeheaven --help
  requires:
    - pip

about:
  home: https://github.com/flakeheaven/flakeheaven
  summary: FlakeHeaven is a [Flake8](https://gitlab.com/pycqa/flake8) wrapper to make it cool.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mcarans
    - weiji14
