{% set name = "flakeheaven" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flakeheaven-{{ version }}.tar.gz
  sha256: eb07860e028ff8dd56cce742c4766624a37a4ce397fd34300254ab623d13047b

build:
  entry_points:
    - flake8heavened = flakeheaven:flake8_entrypoint
    - flakeheaven = flakeheaven:entrypoint
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - colorama
    - entrypoints
    - flake8 >=4.0.1,<5.0.0
    - pygments
    - python >={{ python_min }}
    - toml
    - urllib3

test:
  imports:
    - flakeheaven
  commands:
    - pip check
    - flake8heavened --help
    - flakeheaven --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/flakeheaven/flakeheaven
  summary: FlakeHeaven is a [Flake8](https://gitlab.com/pycqa/flake8) wrapper to make it cool.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mcarans
    - weiji14
